apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels: # these labels are deployment labels
    app: shipping
    project: roboshop
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels: # these labels are used to find the pods
      app: shipping
      project: roboshop
      tier: backend
  template:
    metadata:
      labels: # these labels are pod labels
        app: shipping
        project: roboshop
        tier: backend
    spec:
      containers:
      - name: shipping
        image: sowmya142/shipping:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: shipping

--- 

apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
spec:
  selector:
    app: shipping
    project: roboshop
    tier: backend
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #container-port